language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - '9'
  - '8'
  - '6'
after_success:
  # required for yarn not to fail when installing semantic-release
  # instead it is removed from the dependencies and added as global at the end
  - yarn global add semantic-release && semantic-release || true
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
